# Generated by Django 2.2.6 on 2020-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpage', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.TextField(default='', max_length=10),
        ),
    ]
