# Generated by Django 2.2.6 on 2020-06-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpage', '0004_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
